# Generated by Django 5.1.2 on 2024-11-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendslist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendslist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendslist',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_friend_request'),
        ),
        migrations.AddConstraint(
            model_name='friendslist',
            constraint=models.UniqueConstraint(fields=('friend', 'user'), name='reverse_friend_request'),
        ),
    ]
