# Generated by Django 5.1.2 on 2024-12-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_friendslist_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
