# Generated by Django 5.1.2 on 2024-10-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_currentlyreadinglist_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.bookreview'),
        ),
    ]
