# Generated by Django 5.1.2 on 2024-12-09 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reviewlike_delete_bookreviewmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('waiting', 'Waiting')], default='waiting', max_length=10)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_list_friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_list_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запросы в друзья',
                'verbose_name_plural': 'Запросы в друзья',
                'unique_together': {('user', 'friend', 'status')},
            },
        ),
    ]
