# Generated by Django 5.1.2 on 2024-10-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0007_customuser_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedreadinglist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='plannedreadinglist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reviews',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='status',
            field=models.CharField(choices=[('CR', 'Currently Reading'), ('R', 'Read'), ('P', 'Planned')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('user', 'book')},
        ),
        migrations.DeleteModel(
            name='CurrentlyReadingList',
        ),
        migrations.DeleteModel(
            name='PlannedReadingList',
        ),
    ]
