# Generated by Django 5.1.2 on 2024-10-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(to='books.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
