# Generated by Django 5.1.2 on 2024-10-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_genres_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
